version: "3"

services:
  joomla:
    image: joomla
    restart: always
    container_name: joomlaContainer
    links:
      - joomlaDB:mysql
    ports:
      - 8080:80
    # volumes:
    #   - ./src:/var/www/html
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: password

  joomlaDB:
    image: mysql:5.6
    restart: always
    ports:
      - 3306
    container_name: joomlaDB
    # connects local db to my sql container
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
